# Generated by Django 2.2.4 on 2020-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='cateogry',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='want_to_make',
            field=models.ManyToManyField(related_name='user_wants_to_make', to='login.Registration'),
        ),
    ]
