# Generated by Django 2.2.4 on 2020-08-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_comments_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='title',
            new_name='headline',
        ),
    ]
