# Generated by Django 2.2.4 on 2020-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200824_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='forums'),
        ),
    ]
