# Generated by Django 2.2.4 on 2020-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200824_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
