# Generated by Django 2.2.4 on 2020-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='following',
            field=models.ManyToManyField(to='login.Registration'),
        ),
    ]
